### ISSUE TITLE
Question : How will I use this library for an OAuthed user in my app.

### ISSUE THREAD

**Issue by itslit-tech** [justinhandley/infusionsoft-javascript-api#1]
I have the accessToken and the user's IS Integration name saved in the DB once the user OAuths in my app. What will I need to pass as the first and second parameter when creating an instance of the api i.e.
`var infusionsoft = new api.DataContext('myapp', 'MY_API_KEY');`

I don't have access to the user's API key. Any help will be greatly appreciated.
Thanks.

**Comment by justinhandley** [comment]
So, right now you can't.  This is a legacy code base that I'm working on updating - that is next on my to-do list.  Give me a couple of weeks and we should have it working with auth key.

**Comment by justinhandley** [comment]
Hi There - OK, sorry for the delay.  You can upgrade to 0.2.0 and just pass in your accesstoken instead of te legacy app / key pair and you should be good to go.

var infusionsoft = new api.DataContext('ACCESS_TOKEN');
