### ISSUE TITLE
InvoiceService.createBlankOrder

### ISSUE THREAD

**Issue by acoyfellow** [justinhandley/infusionsoft-javascript-api#3]
Can't seem to figure out what Date format to use here

It does not like the pure Date object, integer, or string based formats at all

```
var api = require('infusionsoft-javascript-api');
var infusionsoft = new api.DataContext("******");
infusionsoft.InvoiceService.createBlankOrder(
  23456, // contact ID,
  'Product Subscription', // invoice name
   new Date().toUTCString(), // can't understand what format to use here?
   0,
   0
)
.then(result => {
    console.log(result);
})
.catch(e => console.error(e))
```

Seems like we're having trouble mapping Javascript date types to the Java datetime format? Unsure, tbh.

Thanks in advance if anyone sees this, and can help.

**Comment by justinhandley** [comment]
So,  I think the right format is  // 2018-08-28T22:31:36-04:00

There are a couple of ways to achieve that.  I often use the moment library for time zone sensitivity in applications, and if you are using that a simple 

`moment().format()`

will do.

I think that `new Date().toISOString()` also produces the same formatting.

**Comment by acoyfellow** [comment]
@justinhandley, thanks for the reply. I tried both suggestions:

`new Date().toISOString()` (which creates string `'2018-08-30T23:56:23.581Z'`) returns:

```'No method matching arguments: java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer'```

`moment().format()` (which creates string `2018-08-30T23:58:15+00:00'`) also returns:

```'No method matching arguments: java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer'```

I'm going to dive deeper, as I need this to work. I'll keep you posted.

edit: even their exact format (https://developer.infusionsoft.com/docs/xml-rpc/#order-create-an-order) `20080908T00:00:00`, set to a future date does not work. Just rejects with same error. Seems to be just reading all of these formats as a string, not a dateTime type

**Comment by justinhandley** [comment]
So.. I just tried this with new Date() and that worked.

Then I tried new Date('2018-08-30T23:56:23.581Z') and that worked.

I went for a date in the future new Date('2018-09-23T23:56:23.581Z') and that worked.

So, I think that you just need a simple date - not a date string, but an actual date in this scenario.

**Comment by acoyfellow** [comment]
@justinhandley that did the trick. Thanks for your help - and the great updated lib :)
