### ISSUE TITLE
Error using InvoiceService.addOrderItem

### ISSUE THREAD

**Issue by TBSliver** [justinhandley/infusionsoft-javascript-api#6]
I keep getting type errors, where this endpoint requires a Double for the price.

Have tried adding CustomType from xmlrpc (https://github.com/baalexander/node-xmlrpc#custom-types) however your version of xmlrpc (~1.1.0) is too old to have this feature.

any chance this can get updated?

**Comment by shadowcat-mst** [comment]
AFAICS the dependency spec should either be updated to a more recent minor release of the xmlrpc client, i.e. ~1.3.0 or similar, or perhaps better still changed to ^1.1.0 to allow any later minor release within 1.x

**Comment by justinhandley** [comment]
@TBSliver - sorry for the slow reply.  I will take a look at this this week and see if I can get an upgrade in place.

**Comment by justinhandley** [comment]
Just checking back in on this..  I am in a pretty full on retreat this week, and as I started to look at this I think it is going to take a little more focus than I have.. If you want to fix it up and submit a pull request feel free, otherwise I will try to get this fixed up next week.

**Comment by justinhandley** [comment]
Hey.. I just pushed a branch to @next - can you do an npm install infusionsoft-javascript-api@next and let me know?  I am doing this because I wanted to get this pushed but haven't had a chance to thoroughly test.  If it works I'll update the official version.

**Comment by TBSliver** [comment]
Unfortunately I no longer have access to the codebase this affected, so cant go back and check this - thanks though!
